In [17]:
!pip install numpy

In [20]:
import numpy as np
arr1 = np.array([1,2,3])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [23]:
np.arange(1,5).reshape(4,1)


array([[1],
       [2],
       [3],
       [4]])

In [29]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.itemsize)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
8
int64
8


In [36]:
a = np.array([1,2,3,4])
b= np.array([5,6,7,8])
print(np.square(a))
print(np.exp(a))

[ 1  4  9 16]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0][0])
print(arr[1:])
print(arr[0:3,1:])

1
[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
